### ISSUE TITLE
how can I do to include material-ui?

### ISSUE THREAD

**Issue by diegoffline** [reactjs/express-react-views#100]
I want to include material-ui in a class

ex: 

var React = require('react');
import Dialog from 'material-ui/Dialog';
import AddIcon from 'material-ui/svg-icons/content/add';
import FloatingActionButton from 'material-ui/FloatingActionButton'

class HelloMessage extends React.Component {
  state = {

	modalOpen: false
}

closeModal(){
	this.setState({
		modalOpen: false

	})

}

openModal(){
	this.setState({
		modalOpen: true
	})

}

render(){
	const style ={
		position: 'fixed',
		right: 50,
		bottom: 50
	}
	return(
	<div> 
	
	<FloatingActionButton style={style}
		onClick={this.openModal.bind(this)} >
		<AddIcon/> 
	</FloatingActionButton>

		<Dialog 
			title="Novo Todo" 
			onRequestClose={this.closeModal.bind(this)}
			open={this.state.modalOpen}>
			
		</Dialog>
	</div>
	)
 }
}

module.exports = HelloMessage;

**Comment by zpao** [comment]
Going to close out since this has been open for a long time. Feel free to comment if you're still having trouble.

**Comment by ivrylobs** [comment]
I also would like to know how to implement Material Ui in every views to render on server. I found the problem is the render method cannot render the style of Material UI.
