### ISSUE TITLE
Express options.settings.views could be an array

### ISSUE THREAD

**Issue by peterlau** [reactjs/express-react-views#108]
Per the [Express 4.x API doc](https://expressjs.com/en/4x/api.html) `options.settings.views` could be a path string or an array. 

> A directory or an array of directories for the application's views. If an array, the views are looked up in the order they occur in the array.

Simply appending a caret as in the existing code below would not work in the latter case
```
    if (!moduleDetectRegEx) {
      // Path could contain regexp characters so escape it first.
      moduleDetectRegEx = new RegExp('^' + _escaperegexp(options.settings.views));
    }
```

**Comment by zpao** [comment]
Shipped the fix in 0.10.4. Thanks!
