### ISSUE TITLE
babel-preset-es2015 has been deprecated

### ISSUE THREAD

**Issue by HughePaul** [reactjs/express-react-views#112]
babel-preset-es2015 has been deprecated

`npm WARN deprecated babel-preset-es2015@6.5.0: We're super 😸  excited that you're trying to use ES2015 syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! `

**Comment by svenkatreddy** [comment]
Thanks @HughePaul for reporting this, there is active PR #115 which addresses this issue. Will give you update once if it is published.

**Comment by svenkatreddy** [comment]
@HughePaul now it's merged to master.

**Comment by lutangar** [comment]
@zpao since the fix #115 for this issue has been merged to `master`, could you publish the new version to `npm`?

**Comment by CharlieEscoboza** [comment]
@zpao Are you the only person allow to publish this package?

**Comment by zpao** [comment]
v0.10.5 is published with this. Sorry for the delay.
