### ISSUE TITLE
Simple Example error after NPM install -> NPM start

### ISSUE THREAD

**Issue by thomasbyoung** [reactjs/express-react-views#116]
Hi, I was trying to deploy a project to Heroku and ran into some issues. So to figure the issue I was going to test deploy the simple example within the repo, but even trying to run it locally doesn't seem to work.

I have followed the instructions for NPM install then NPM start, 

The error I am getting is ::

$ npm start

> application-name@0.0.1 start ../express-react-views/examples/simple
> node app.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'react'

Any help could be helpful - thank you.

**Comment by svenkatreddy** [comment]
@thomasbyoung did you do `npm install` on parent directory (root) ?
and also you need to do npm install on /examples/simple (which i think you did it)

**Comment by svenkatreddy** [comment]
can you please paste your npm install output and error stack ?

**Comment by thomasbyoung** [comment]
This worked, sorry I did not realize I needed to install the main root. 

Thank you.
