### ISSUE TITLE
Update to Babel 7

### ISSUE THREAD

**Issue by arthurfranca** [reactjs/express-react-views#126]
Please update code and package.json to use `@babel/register, @babel/preset-env and @babel/preset-react` as new babel core isn't compatible to old packages (babel-preset-env, babel-preset-react and babel-register)

**Comment by evert1989** [comment]
I see that the merge request has been merged, but when I do a `npm install` it still pulls the `0.10.5` release from January without the babel 7 update.

Is there a new release planned that will include the babel 7 update?

**Comment by zpao** [comment]
v0.11 is now published with this.
