### ISSUE TITLE
Best way to include IE conditional markup in <head>?

### ISSUE THREAD

**Issue by stereosteve** [reactjs/express-react-views#13]
Using the DefaultLayout example from the readme, is there any way to render IE conditional markup like this:

```
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
```

The best thing I came up with was to use `dangerouslySetInnerHTML` for the entire head tag... is there a better way?

**Comment by zpao** [comment]
There is unfortunately not a better way. We don't have any method for inserting comment nodes in React. Perhaps some option to the engine creation but that doesn't sound super awesome to me so I'm not really inclined to do that.

**Comment by spicyj** [comment]
See https://github.com/facebook/react/issues/2810.
