### ISSUE TITLE
Dynamic example is vulnerable to XSS

### ISSUE THREAD

**Issue by Alexendoo** [reactjs/express-react-views#146]
https://github.com/reactjs/express-react-views/blob/934ff60446101d0001eb45496f72966e9c42e051/examples/dynamic/views/Html.js#L51

Only "script" is escaped, so we can work around that

```diff
diff --git a/examples/dynamic/app.js b/examples/dynamic/app.js
index 1c405b6..cb8c81c 100644
--- a/examples/dynamic/app.js
+++ b/examples/dynamic/app.js
@@ -13,7 +13,7 @@ app.get('/', function(req, res) {
     items: [
       'document your code',
       'drop the kids off at the pool',
-      '</script><script>alert(666)</script>',
+      '</SCRIPT><SCRIPT>alert(666)</SCRIPT>',
     ],
     text: '',
   };
```

**Comment by zpao** [comment]
Eh, it's just an example and not meant to be a definitive way to use this. The dynamic example isn't officially supported as a pattern anyway. Appreciate the vigilance though :)

**Comment by Alexendoo** [comment]
@zpao I found this through a discussion with somebody who used the same technique in Html.js to escape in their own small templating function (they felt that ejs/etc was overkill)

When I pointed out that their function was vulnerable to XSS they linked me to where they adapted it from:

https://github.com/reactjs/express-react-views/blob/8fdfa85fffefa26e0930c0e24057efb881504ec4/examples/dynamic/views/Html.js#L12-L51

They said they trusted it to be correct, which is a completely understandable. It has a convincing comment and is hosted under https://github.com/reactjs

If it's unsupported I'd recommend removing the example, since it's rather unsafe
