### ISSUE TITLE
Dealing with different file extensions for production

### ISSUE THREAD

**Issue by sslotsky** [reactjs/express-react-views#153]
This is more of a best practices question, I guess? I think many people have their views defined in `.jsx` or `.tsx` files, but when they compile, those files just become `.js` files. I find myself checking `process.env.NODE_ENV` to determine which extension I can use. Is there a better way? I'm using `.tsx` but again, I assume many who use `.jsx` would have the same issue, no?

**Comment by artemyarulin** [comment]
We have such code at the start of the app, works fine:

```ts
const viewExt = process.env.NODE_ENV === 'production' ? 'js' : 'tsx'
app.set('view engine', viewExt)
app.engine(viewExt, require('express-react-views').createEngine())
app.set('views', __dirname + '/views')
```
