### ISSUE TITLE
How to input (redis) database info into React templates/props?

### ISSUE THREAD

**Issue by bnb** [reactjs/express-react-views#16]
I am trying to build my first app, and I'm using a Redis/Express/React stack, with express-react-views doing the rendering of my React templates. I've followed the README.md pretty well, but would now like to include data from my database into the React templates. 

How can I go about doing that? My best guess is adding a callback to `app.get('/', require('./routes').index);`, which somehow inserts the database data into props or JS `var`s (which would then get put into React somehow?). That part is what I would like to know. 

Thanks,
&!

**Comment by Evanion** [comment]
could you please clarify for th rest of us? :)
