### ISSUE TITLE
Is this reactive?

### ISSUE THREAD

**Issue by Core-commits** [reactjs/express-react-views#162]
I'm used to stuff like Mustache, handlebars or ejs, is this reactive?

**Comment by arifemir** [comment]
makes similar behavior to other template engines

**Comment by vprasanth** [comment]
> I'm used to stuff like Mustache, handlebars or ejs, is this reactive?"

It's exactly the same as the template engines you've mentioned. The server gets a request, compiles a view, returns a static HTML document. This engine allows you to write your templates using React components and JSX. There is no React runtime, so no client-side processing (similar to all view engines).

**Comment by Core-commits** [comment]
thank you, appreciated
