### ISSUE TITLE
Documentation for createEngine() example is incomplete?

### ISSUE THREAD

**Issue by aredridel** [reactjs/express-react-views#20]
The example shows:

```
app.engine('jsx', require('express-react-views').createEngine());
```

But that doesn't work, giving:

```
TypeError: Cannot read property 'jsx' of undefined
```

because it expects a jsx key in the configuration:

```
app.engine('jsx', require('express-react-views').createEngine({ jsx: {} }));
```

works however.

**Comment by zpao** [comment]
Thanks for the heads up. It's not that the documentation was wrong, just that the code was!

I fixed it (5f67270aa82f6e69c1322f3264e360591320dca3) and pushed 0.7.1.
