### ISSUE TITLE
ES6 template is not working

### ISSUE THREAD

**Issue by unbug** [reactjs/express-react-views#28]
How to make ES6 template working?
```
<DefaultLayout title={this.props.title}>
        <script dangerouslySetInnerHTML={{__html:`
          function test(a){
            alert(a);
          }
          test();
        `}} />
</DefaultLayout>
```
I got error `React.createElement("script", {dangerouslySetInnerHTML: {__html:` ^ Unexpected token ILLEGAL`

**Comment by zpao** [comment]
Are you specifying `harmony: true` when creating the engine?

**Comment by unbug** [comment]
I though it was the default setting,now it works like a charm!
