### ISSUE TITLE
recommendations for serving front end?

### ISSUE THREAD

**Issue by SOSANA** [reactjs/express-react-views#30]
Hidy ho friends,

Curious what your recommendations are for serving front end with react.js and mounting those views on the client along side express-react-views?

**Comment by landau** [comment]
You'll have to re-render on the front end. The server produces html. So, the server should provide a `mount` for the client to render into.

**Comment by zpao** [comment]
There have been discussions in PRs about server side rendering and mounting. There's an example of making this work in a bit of a hacky way. Other ways need more handled before they'll work properly. Take a look through those.
