### ISSUE TITLE
SyntaxError on Windows

### ISSUE THREAD

**Issue by gocreating** [reactjs/express-react-views#32]
It seems that the jsx view files will raise syntax error on windows(my os is win 8.1 64bit),
but it works well on my mac.

anybody meet the same problem?

**Comment by mpawlow** [comment]
@gocreating Yes. See: https://github.com/reactjs/express-react-views/issues/33.
Is this the same issue you encountered?

**Comment by zpao** [comment]
Going to close this and continue in #33.
