### ISSUE TITLE
CJSX (CoffeeScript) support

### ISSUE THREAD

**Issue by screendriver** [reactjs/express-react-views#34]
Is it possible to use `CJSX` (CoffeeScript) files? If yes: how?
Do I have to install [coffee-react-transform](https://github.com/jsdf/coffee-react-transform)?

**Comment by zpao** [comment]
Just installing that won't help, we install a require hook and transform ourselves (well, delegating to babel). We could potentially make the transform step injectable but we'd need to bake support for that into our package directly (calling out to coffee-react-transform). I don't have any desire/time to add this myself but I wouldn't be opposed if you're interested!

**Comment by ScreenDriver** [comment]
Thank you for that information. I would make a pull request but unfortunately I am completely new to this whole NodeJS / Express thing so I am too unexperienced in implementing anything like this. :disappointed:

**Comment by juniorg** [comment]
See package https://www.npmjs.com/package/express-coffee-react-views (a fork of this one BTW)
It may be what you are looking for.

**Comment by zpao** [comment]
Looks like there hasn't been any drive to get this in so I'm going to close out.
