### ISSUE TITLE
A better way to work with web components?

### ISSUE THREAD

**Issue by unbug** [reactjs/express-react-views#42]
Due to JSX's rule,we can't put a custom element in reactjs.For now I could come up the idea is 
```html
<div dangerouslySetInnerHTML={{__html:`
            <paper-button></paper-button>
            `}}/>
```
Is there a better way to do this?

**Comment by spicyj** [comment]
This should already work correctly in the latest version of React.

```js
<div><paper-button></paper-button></div>
```

compiles to

```js
React.createElement("div", null, React.createElement("paper-button", null))
```

and should render properly.

**Comment by unbug** [comment]
@spicyj I actually wont to get rid of the `div` wrap.Just
```html
<paper-button></paper-button>
```
