### ISSUE TITLE
Babel view caching

### ISSUE THREAD

**Issue by ethanjdiamond** [reactjs/express-react-views#45]
Hi reactjs team,

I'm using this library, but it looks like babel's caching my jsx views. According the to the docs, this feature is disabled "in development." Is there an environmental variable or something I have to set for express-react-views to consider me being in a dev environment?

**Comment by zpao** [comment]
This uses express' `env` setting, which is set to `NODE_ENV` environment variable (or default of `'development'`). When `=== 'development'`, the views should be getting cleared.

**Comment by zpao** [comment]
Going to close out, this is working to the best of my knowledge.
