### ISSUE TITLE
Make the use of Babel 'only' setting optional?

### ISSUE THREAD

**Issue by michaeljones** [reactjs/express-react-views#47]
Very happy users of this project, thanks for releasing it.

I have just started using more es6 syntax in the rest of my code which is outside of the 'views' folder. Unfortunately as Babel is initialised with the `only` setting set to the `views` folder, the rest of my code is not automatically translated from es6 and so errors.

Would it be possible to make this setting optional in some way? Or is there a preferred way to approach this situation? I tried running my server with `babel-node` but that still fails. I suspect that the `babel/register` call in this code base might be resetting the babel options but that is purely a guess.

Any advice welcome. Thanks.

**Comment by zpao** [comment]
This is effectively the same as #40 (fix coming), so going to close out.

**Comment by michaeljones** [comment]
Ah, sorry for not checking through the other issues properly. Not cool.

Thanks for the quick reply and the fix.
