### ISSUE TITLE
Enables React 0.14

### ISSUE THREAD

**Issue by ludovic-gonthier** [reactjs/express-react-views#49]
It would be great to be able to use the new version of react in this module.I don't know if this implies code changes or just packages.json `peerDependencies` updates.

**Comment by zpao** [comment]
I'll do this after 0.14 final ships.

**Comment by ludovic-gonthier** [comment]
Ok, should I close the issue if it's already planned?

**Comment by zpao** [comment]
Nah, let's leave it open and I'll close it with the commit. Thanks for filing!

**Comment by uptownhr** [comment]
0.14 shipped!

**Comment by zpao** [comment]
I just shipped 0.9 which uses React 0.14
