### ISSUE TITLE
Clear cache not work after render throws exception

### ISSUE THREAD

**Issue by lijunle** [reactjs/express-react-views#52]
Repro steps:

1. In development mode, render a view which throws exception. For example, `TypeError: Cannot read property 'length' of undefined`.
2. Add `console.log` to the view for debugging the issue.
3. Console output nothing.
4. Restart server, console comes back.

I am not sure if it is related to Babel (#45).

**Comment by granteagon** [comment]
From what I can tell from Express ([#542](https://github.com/strongloop/express/issues/542)), express caches the view function, but not the view template.  Since jsx components are functions, it may be caching them.
