### ISSUE TITLE
How do I set this up with Gulp?

### ISSUE THREAD

**Issue by leian-ivey** [reactjs/express-react-views#57]
I'm using node and docker to run my server and need a way to compile the react code with gulp.

**Comment by fbukevin** [comment]
[https://www.npmjs.com/package/gulp-react](https://www.npmjs.com/package/gulp-react)

Is this what you need?

**Comment by zpao** [comment]
This project is focused on server-side rending of components. You'll want something else if you are precompiling assets for the client.
