### ISSUE TITLE
Updated Example with Express 4 and BabelJS

### ISSUE THREAD

**Issue by rbaindourov** [reactjs/express-react-views#61]
Hi There,

I am trying to create a CMS that uses ReactJS as the view layer.

The CMS itself should be the latest version of Express and using BabelJS to give me ES2015 syntax all throughout the project.

I am kind of a laymen when it comes the the differences between Express 3.5 vs 4.x.

So I was hoping someone could either update the examples, or give me a few pointers.

Here is my project on github: [multiDomainCMS](https://github.com/rbaindourov/multiDomainCMS)

So far no major bugs that I couldn't fix myself. 

But I could really use some pointers on deploying this to production!

Thanks for all your hard work!

-Robert Baindourov

**Comment by zpao** [comment]
I know you're probably way past this but here goes…

Nothing in the upgrade from express 3 to 4 should relate to the view engine. I've used http://expressjs.com/en/guide/migrating-4.html in the past and actually just used it to upgrade the simple example here (https://github.com/reactjs/express-react-views/commit/80163d8f7e3fdb3f34d349d6712d15ac8720d95f). Hope that helps you or somebody in the future.
