### ISSUE TITLE
Very slow if render more than 50 entries

### ISSUE THREAD

**Issue by unbug** [reactjs/express-react-views#64]
I am sure it is not the mongodb issue,because I have another api to get more than 50 entries each request,pretty fast,but when render with express-react-views,it's take more then 3's to get it done.
My page has 4 components,each has two or one loops for the data,I don't think this will be the issue for javascript,and the whole response only has 3KB.Is there any thing I can do?

**Comment by zpao** [comment]
Make sure you're running express in production mode (`NODE_ENV=production node server.js`), which will also affect React.

Otherwise, yes this will be slower than a pure data endpoint and slower than other templating options like handlebars.

**Comment by unbug** [comment]
Thanks @zpao
