### ISSUE TITLE
Can't include attributes for <head>

### ISSUE THREAD

**Issue by saiichihashimoto** [reactjs/express-react-views#70]
I'm trying to implement [opensearch with autodiscovery](http://www.opensearch.org/Specifications/OpenSearch/1.1#Autodiscovery_in_HTML.2FXHTML), which requires  ```<head profile="http://a9.com/-/spec/opensearch/1.1/">``` property but the profile property gets stripped away. Quite by accident, I discovered that it doesn't do this in the case of ```<head property="anything">```, which is quite odd.

**Comment by saiichihashimoto** [comment]
I'm realizing now that this is most likely a react issue rather than an express-react-views issue but, just in case it isn't, I'll leave this open for confirmation.

Link to issue in react: https://github.com/facebook/react/issues/6029

**Comment by zpao** [comment]
Good realization :) I'll close this out.
