### ISSUE TITLE
Partial support es6 classes

### ISSUE THREAD

**Issue by randomailer** [reactjs/express-react-views#72]
I create es6 react view. I have some problem with static props and instance props

``
Unexpected token (7:18)
export default class CurrentProduct extends React.Component {
     static errors = {
                   ^
    }
``

**Comment by zpao** [comment]
If you need different babel options than the default, you must pass those in when creating the engine. In this case, the property initializers transform is not part of the es2015 or react presents so you must install and specify more.

```js
require('express-react-views').createEngine({
  babel: {
    preset: [...],
    plugins: [...],
  }
})
```
