### ISSUE TITLE
how to manage onsubmit event of a form

### ISSUE THREAD

**Issue by ningappa** [reactjs/express-react-views#76]
Hi I'm a beginner to react. I understand that express-react-views can handle  the server side rendering of view. In that i don't need to write javascript externally. correct me if i'm wrong,

Now I was going through the react tutorial https://facebook.github.io/react/docs/tutorial.html.
I want to handle the onsumit event of a form,
```
var AuthForm = React.createClass({
    handleSubmit: function (e) {
        e.preventDefault();
        console.log("submit event fired!!")
       // do something
    },
    render: function () {
        return (
                    <form className="AuthForm"  onSubmit={this.handleSubmit}>
                                <input type="text" placeholder="Username" />
                                <input type="text" placeholder="code" />
                                <input type="submit" value="Login" className="button" />
                    </form>
               );
    }
})
```

**Comment by toberoo** [comment]
So this library is intended to replace html/jade/mustache templates. It is a way to use react to deliver static information. Rendering dynamic components require some workarounds, check out : https://github.com/reactjs/express-react-views/blob/master/examples/dynamic/views/Html.js and the dynamic example in general. Saying that, I feel like the form submit shouldn't require that.

**Comment by zpao** [comment]
This project doesn't do anything client-side at the moment. If you would like to run React code on the client you'll have to manage that yourself (there's 1 example in the repo and a couple PRs with attempts to integrate better).
