### ISSUE TITLE
View Cache not being cleared in development

### ISSUE THREAD

**Issue by jkieley** [reactjs/express-react-views#80]
The view cache is not being cleared and requires an application restart everytime. 
Even when NODE_ENV=development

**Comment by zpao** [comment]
Last I checked this was working for me. Can you be more specific with your set up / OS? Could be the same as #68.

**Comment by jkieley** [comment]
System Software Overview:
      System Version: OS X 10.10.5 (14F1808)
      Kernel Version: Darwin 14.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal

node version: v4.2.4

Here is the full path to my views directory:

`/Users/james.kieley/git/partner-offers/views/`

**Comment by zpao** [comment]
Thanks for following up. I think this is the same issue & the `.` is being used in the regexp. Fix incoming.
