### ISSUE TITLE
How to use es6 in views ?

### ISSUE THREAD

**Issue by ritsuyan** [reactjs/express-react-views#81]
can I create a  a  js type views in the ./views and use the es6 to write?

**Comment by zpao** [comment]
Yes. The default babel setup transforms es2015 and react.

**Comment by ritsuyan** [comment]
Thx, but faced a new problem: the project initial is React-Router , and i just add a new route in server.js then when i bowser : localhost:3000 
error:
   Uncaught Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function but got: object

but exactly I check the all components out  and find no error , it  is conflicted ?
