### ISSUE TITLE
is it  conflict with React-router ?

### ISSUE THREAD

**Issue by ritsuyan** [reactjs/express-react-views#82]
I just add a simple react views then find following error and the project initial is the React-router
error:
Uncaught Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function but got: object

but exactly I check the all components out and find no error , it is conflicted ?

**Comment by zpao** [comment]
Much to do here without seeing code. I would look at the line number & stack and see what the object is. It could be an issue with import/export and objects. react-router shouldn't be an issue, but you probably don't need it. As a reminder, this project is entirely server-side rendering without a client-side component.

**Comment by ritsuyan** [comment]
@zpao  
Thx & appreciate it  , and this may be my last question :   
  I just find that cannot use a js file type in ./views but only could use jsx ,and I  want to use es6 grammar in views 
how could I do ?
I  try to use babel-register in the jsx file and write es6 codes  but  no much to do there and catch a error.

**Comment by zpao** [comment]
I encourage you to start with a working example like we have in the examples folder and progressing from there. Test each step of the way and you'll be able to better determine at what point something stops working and can pinpoint the blame far better.
