### ISSUE TITLE
React element like button can not respond to click function

### ISSUE THREAD

**Issue by lenvonsam** [reactjs/express-react-views#84]
hi @zpao 
i clone ur example simple project, then the project is running normally.
But I find that the button element in index.jsx can not work when i add click function. 
Could you help me to solve this problem? thx

screenshot following:
![image](https://cloud.githubusercontent.com/assets/10168476/15972354/a4aff1a0-2f70-11e6-88a3-f7ba7b53d1f3.png)
![image](https://cloud.githubusercontent.com/assets/10168476/15972446/1a02dc92-2f71-11e6-86c7-17647510935f.png)

**Comment by zpao** [comment]
Your screenshot shows you are trying to call `hindleClick`, which looks
like a typo.

Regardless though, this project is explicitly about server side rendering
and doesn't support client sound mounting. If you want that, you can do a
little more - the dynamic example shows that.

**Comment by lenvonsam** [comment]
ok , thx@zpao, i will try to have a trial on  the dynamic example as soon as i can.

**Comment by agungsb** [comment]
Hi, I'm facing the same problem. Have you solved this?

**Comment by zpao** [comment]
This project is still about server-side rendering so going to close out.
