### ISSUE TITLE
preserving onClick markup

### ISSUE THREAD

**Issue by aocenas** [reactjs/express-react-views#92]
Hi,
I would like to know if there is a way to preserve onClick in a classical server side way in sense that it will go into html markup. For example:

```
<button onClick={`ga('send', 'event');`}>
```

Basically I need the onClick to be preserved verbatim. Only way to keep the functionality, that I know of, would be to add some `<script>` with some classic jquery click handler somewhere but I wonder if there is some easier way.

**Comment by renanborgez** [comment]
Yes, i need the same! I want call a custom js function but is impossible

**Comment by Lucifier129** [comment]
try `dangerouslySetInnerHTML`

**Comment by zpao** [comment]
I understand the desire for this but this isn't something I think we should support (it's also probably not easy or even doable without some big hacks). Your best bet is something more externalized or take a look at the dynamic example which renders the React after the fact.

**Comment by artemyarulin** [comment]
I was migrating existing HTML/JS codebase and just had the same issue, rewriting whole thing wasn't a choice, so solved it using terrible hack:

```html
<button data-onclick="functionToCall" />
<script>
  $('button[data-onclick]').click(function() { eval($(this).attr('data-onclick')) })
</script>
```

Don't use it for production :)

**Comment by neirongkuifa** [comment]
> try `dangerouslySetInnerHTML`

Works perfectly for me!
