### ISSUE TITLE
Res.locals on React

### ISSUE THREAD

**Issue by picorelli** [reactjs/express-react-views#96]
Hello! How can I access data from res.locals on react view? For example, I'm using passport.js where I can put some data about an authenticated user and then can be accessed in client side.

**Comment by sumbad** [comment]
Hi, I think you can put it into an script section. Something like this:

```
export default class Index extends React.Component{
  render() {
    let scripts: JSX.Element[] = [];
    scripts.push(<script dangerouslySetInnerHTML={{
      __html: `
      var data = ${JSON.stringify(this.props.data).replace(/script/g, 'scr"+"ipt')};
      `}} />);

    return (
      <Layout title={this.props.title} links={links} scripts={scripts}>
   ...
```

or just use AJAX request in client side.

**Comment by zpao** [comment]
`res.locals` is passed to the top-level component you render as `props`. To be fair, I've only used the `res.render(view, locals)` pattern so I'm not sure if setting `res.locals.foo` separately is different but I would expect it to work. We can fix it if not.

If you want that value in JS client-side you'd need to figure that out on your own. What @sumbad here is a good start. The dynamic example we have is another place to start looking. Hope that helps!

**Comment by 7h3w4rd0c70r** [comment]
@zapo Hi, So how so did you figured out the setting locals with res.locals['abc123']? I'm trying to pass a variable _userdata to my menu.jsx view. But instead of passing it through four different components' props, it would be so much easier to just set res.locals['_userdata'] = {...} in the middleware and then access it in one of the nested components with this.props['_userdata']. This currently doesn't work for me. What do you think about this issue?
Btw. @zpao Thank you so much for you work on express react views, you made my life just easier and cleaner.. :)

**Comment by AdventureBear** [comment]
Hello, I'm having this same issue and I don't know if it's a problem that I don't understand react well enough still.  

I have middleware passing the currentUser from req.user like this: 

```
> app.use(function(req, res, next){
>   //console.log("Current User: " + req.user)
>   res.locals.currentUser = req.user;
>   res.locals.error = req.flash("error")
>   res.locals.success = req.flash("success")
>   next();
> });
```
and in template client side can access it as currentUser.  But I can't figure out how to access that via a React component even though it seems like it should be able to access it as well. Thanks for any suggestions.

**Comment by macvay** [comment]
If you're using response.locals in the middleware you can get an access to it via props._locals in the view rendered by react engine.
Props object in React view will have 3 presetted properties: settings, cache, _locals.  + props properties initialized via res.render("view", {prop:something});
